### ISSUE TITLE
Publishing the newest package version to conda

### ISSUE THREAD

**Issue by mbdabrowska1** [epi2me-labs/aplanat#3]
Hi, any chance of publishing the most recent version of aplanat to bioconda?

**Comment by cjw85** [comment]
Hi Magda!

We no longer publish to bioconda, because the process is slow and laborious. We have our own conda channel:

```
mamba install -c epi2melabs -c conda-forge -c bioconda "epi2melabs::aplanat"
```

**Comment by mbdabrowska1** [comment]
That's understandable! Installing it from your own channel is perfectly fine for what I need, thank you!
